### ISSUE TITLE
python-dateutil missing from requirements.txt

### ISSUE THREAD

**Issue by spameier** [radiorabe/suisa_sendemeldung#225]
Got this error on a fairly vanilla Fedora 36 installation:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/suisa_sendemeldung/suisa_sendemeldung/suisa_sendemeldung.py", line 24, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by hairmare** [comment]
I seem to have missed putting it into requirements because it's a transitive dependency of something in requirements-dev.txt
